### ISSUE TITLE
Improve visualization

### ISSUE THREAD

**Issue by ciliasw** [openearth/sandbox-fm#15]
### A few visualization issues (don't know the current status!)

- improve bathy projection by using original Sandbox colour map and shading interp function instead of flat

- issue with colour fading of dots for current animation 

- improve brightness of background satellite image

**Comment by SiggyF** [comment]
- Faded dots fixed partly by watermask, partly by disabling the "presentation mode" in beamer, 
which flattened all the colors.  
- Reuse natural colormaps
