### ISSUE TITLE
Bug in sandbox2model depths 

### ISSUE THREAD

**Issue by ciliasw** [openearth/sandbox-fm#4]
Something goes wrong in the conversion from sandbox depths to model depths: 

- the flat (table) surface is translated into an oblique surface

- large depths and zero depths appear on the edges of the sandbox depths

![image](https://cloud.githubusercontent.com/assets/25451406/22455747/dffbd8a6-e78e-11e6-842d-88e0f180d737.png)

**Comment by SiggyF** [comment]
Is this fixed by the new `sandbox-fm anomaly` command?

**Comment by ciliasw** [comment]
Ha Fedor, ja dit is verholpen, kan dus gesloten worden!

Gr.Cilia
